CC=gcc
TGTDIR=./
IDIR=./includes/
SRCDIR=./srcs/
OBJDIR=./obj/
TARGET=$(TGTDIR)libft.a
SRCS=$(SRCDIR)*.c
DEPS=$(IDIR)ft.h
CFLAGS=-I$(IDIR)

all: libft.a

$(TARGET): $(SRCS)

clean:

fclean: clean


re: fclean all
